### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np

arr = np.random.randint(1, 21, size=(5, 5))
arr[:, 2] = 1
arr

array([[ 2,  7,  1, 10,  5],
       [10, 20,  1,  1, 13],
       [19,  8,  1, 15, 14],
       [ 1, 19,  1, 18,  3],
       [ 7, 19,  1, 12,  8]], dtype=int32)

In [2]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(arr2, 0)
arr2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [ ]:
#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr3 = np.arange(1,37).reshape(6,6)
print(arr3)
subArray = arr3[2:5,1:4]
print(subArray)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]
