In [12]:
import numpy as np

data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(data)

print(np.mean(data))
print(np.median(data))
print(np.std(data))

print(data[0:1,0:])
print(data[2:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
6.5
6.5
3.452052529534663
[[1 2 3 4]]
[[11 12]]
